// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnvvccuehmmbghossyqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdudnZjY3VlaG1tYmdob3NzeXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQ3MjQsImV4cCI6MjA2NTIyMDcyNH0.4htoxYScVIpaGDWJlxcUTP0-KfeuKvJ3yLM2Hjmv72A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);